### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ReplayDEVYT** [ReplayDEVYT/MTC-C-Database#2]
On server launch, error appears
`TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at PostDbLoadService.applyFleaPriceOverrides (C:\snapshot\src\services\PostDbLoadService.ts:518:43)
    at PostDbLoadService.performPostDbLoadActions (C:\snapshot\src\services\PostDbLoadService.ts:122:14)
    at GameController.load (C:\snapshot\src\controllers\GameController.ts:91:32)
    at GameCallbacks.onLoad (C:\snapshot\src\callbacks\GameCallbacks.ts:37:29)
    at App.load (C:\snapshot\src\utils\App.ts:53:26)
TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at PostDbLoadService.applyFleaPriceOverrides (C:\snapshot\src\services\PostDbLoadService.ts:518:43)
    at PostDbLoadService.performPostDbLoadActions (C:\snapshot\src\services\PostDbLoadService.ts:122:14)
    at GameController.load (C:\snapshot\src\controllers\GameController.ts:91:32)
    at GameCallbacks.onLoad (C:\snapshot\src\callbacks\GameCallbacks.ts:37:29)
    at App.load (C:\snapshot\src\utils\App.ts:53:26)`
    
Does not seem to have effect on gameplay

**Comment by ReplayDEVYT** [comment]
fixed
